### ISSUE TITLE
Using the example "mini" config: `IndexError: index 0 is out of bounds for axis 0 with size 0`

### ISSUE THREAD

**Issue by Arno500** [criteo/hwbench#41]
When graphing, after recording data using [this configuration](https://github.com/criteo/hwbench/blob/main/configs/mini.conf), I get the following output:
```
Traceback (most recent call last):
  File "/home/arno/.local/bin/hwgraph", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/arno/.local/share/uv/tools/hwbench/lib64/python3.12/site-packages/graph/hwgraph.py", line 376, in main
    args.func(args)
  File "/home/arno/.local/share/uv/tools/hwbench/lib64/python3.12/site-packages/graph/hwgraph.py", line 61, in render_traces
    rendered_graphs += graph_environment(args, output_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arno/.local/share/uv/tools/hwbench/lib64/python3.12/site-packages/graph/hwgraph.py", line 234, in graph_environment
    rendered_graphs += graph_chassis(args, bench_name, output_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arno/.local/share/uv/tools/hwbench/lib64/python3.12/site-packages/graph/chassis.py", line 139, in graph_chassis
    y_serie = np.array(serie[trace.get_name()])[order]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
```

The following command was used:
```
hwgraph graph --traces ./hwbench-out-20241025234750/results.json:CPU:CPU.package --outdir ./graphs
```
but there was the same issue using:
```
hwgraph graph --traces ./hwbench-out-20241025234750/results.json:CPU:CPU.package --traces ./hwbench-out-20241025234750/results.json:Server:BMC.Server ./hwbench-out-20241025234750/results.json:Chassis:BMC.Chassis --outdir ./graphs
```

Attached is my `results.json`: [results.json](https://github.com/user-attachments/files/17528052/results.json)

Seeing the graphs, it is probably because the `mini` config is too mini and does not have the time to gather more than 1 data point, making the graph renderer crash.

**Comment by ErwanAliasr1** [comment]
https://github.com/criteo/hwbench/pull/42
